### ISSUE TITLE
Transform Animations not working  in latest release

### ISSUE THREAD

**Issue by wave-electron** [kcoley/gltf2usd#100]
@kcoley  In your latest release - transform animations no longer seem to work. The cubeBounce I posted earlier is no longer working anymore (which you did have working in the Sept release... I also have other transform animations that no longer work.  

I haven't been trying every version of the script  with each new commit, so can't pinpoint the time it was introduced. I just downloaded the latest today and tested it... in a fresh directory separate from my earlier versions. 

I checked some multiple bone animations and they are converting without issue. Just seems like transform animations, the keyframes are on a nested mesh to the root mesh as in cubeBounce  

[cubeBounceFiles 2.zip](https://github.com/kcoley/gltf2usd/files/2568172/cubeBounceFiles.2.zip)

**Comment by wave-electron** [comment]
It appears to have got broken again on the 22nd Oct after you did more work on the transform code, it was working on the 9th Oct after we worked out the script was not working for multiple transforms and you fixed the for loop so it handled more than 1.

**Comment by kcoley** [comment]
Hi @wave-electron !
I made a change to the animation export on October 21 to only use the first animation group in a glTF file.  Problems occurred if multiple animation groups in the glTF file try to animate the same animation channels of a mesh, which causes the export to fail.  If you drag your original glTF to the Babylon.js glTF viewer, you will see the same behavior which is currently exported: https://gltfviewer.babylonjs.com

The solution for this would be to modify the glTF file so all animations that you want in the USD file are in the first animation group.  I was able to tweak your glTF file manually and move all the animations into the first animation group to get the behavior that worked before: 
[cubeBounceAnimationsCombined.zip](https://github.com/kcoley/gltf2usd/files/2568493/cubeBounceAnimationsCombined.zip)

In the process of doing this, I found another bug, which I was able to fix and merge to master: https://github.com/kcoley/gltf2usd/pull/101

Let me know if this makes sense and feel free to reopen if the issue persists!

**Comment by wave-electron** [comment]
@kcoley  Good news, I don't have to change my workflow! I found a way to create a single NLA track from multiple transform animations like the bouncing cube without having to manually edit the GLTF file after an export! 

Having this issue the past two days was a" blessing in disguise", as it has helped me better understand my own workflow and how the NLA editor works in Blender :)

**Comment by kcoley** [comment]
@wave-electron great news!

**Comment by enzyme69** [comment]
@wave-electron @kcoley I think I might be going mad because the transformation animation is not working anymore https://github.com/kcoley/gltf2usd/issues/111
