### ISSUE TITLE
No PIL or Pillow module? Strange.

### ISSUE THREAD

**Issue by enzyme69** [kcoley/gltf2usd#103]
Hello I am back, I downloaded the latest gltf2usd but when running I am getting this error. I am sure I have PIL module. This is so weird.

```
Traceback (most recent call last):
  File "gltf2usd.py", line 16, in <module>
    from PIL import Image
ImportError: No module named PIL
```

**Comment by enzyme69** [comment]
If I use Python 3:
```
Traceback (most recent call last):
  File "gltf2usd.py", line 18, in <module>
    from pxr import Usd, UsdGeom, Sdf, UsdShade, Gf, UsdSkel, Vt, Ar, UsdUtils
  File "/Users/jimmygunawan/Projects/Pixar/BUILD/lib/python/pxr/Usd/__init__.py", line 24, in <module>
    import _usd
ModuleNotFoundError: No module named '_usd'
```

**Comment by enzyme69** [comment]
192-168-1-7:USDZ_TotoroSimple jimmygunawan$ pip install pillow
Requirement already satisfied: pillow in /usr/local/lib/python2.7/site-packages (5.3.0)
192-168-1-7:USDZ_TotoroSimple jimmygunawan$ python gltf2usd.py 
Traceback (most recent call last):
  File "gltf2usd.py", line 16, in <module>
    from PIL import Image
ImportError: No module named PIL
192-168-1-7:USDZ_TotoroSimple jimmygunawan$ 

... I am getting crazy...

**Comment by enzyme69** [comment]
If I use virtualenv, and inside Python running: from pxr import Usd it crashes Python......
If I am outside running python, running: from pixr import Usd -- it works! But It does not load PIL...

**Comment by enzyme69** [comment]
I am using Apple's Pixar USD Bundle.

**Comment by enzyme69** [comment]
I have to do this:

sudo nano ~/.bash_profile

export PATH=$PATH:$HOME/USDPython/USD
export PYTHONPATH=$PYTHONPATH:$HOME/USDPython/USD
export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/site-packages

It's so weird, anyhow, it's still pretty annoying that virtualenv one crashing Python, but the main one works. And I also made a new Account cleanly installing Apple's Pixar USD build, and then I still need to do bash_profile stuff and yeah... it works without Python crashing.

**Comment by enzyme69** [comment]
Just for my future me or anyone with such issue:
- you have multiple pythons...
- Mac comes with its own Python 2.7
https://stackoverflow.com/questions/122327/how-do-i-find-the-location-of-my-python-site-packages-directory
- pip install does not always install to the correct site-packages
- do: which python to check which python is running

<img width="873" alt="screen shot 2018-11-16 at 12 15 47 am" src="https://user-images.githubusercontent.com/3952687/48555265-c9528600-e934-11e8-8fdf-31c86af874bc.png">

In the past I have been using conda / anaconda / mini-conda, but better of using virtualenv and watch Coding Train video tutorial on it.

But using virtualenv I ended keep crashing if Python USD install is using the one from Apple... it's a headache...

**Comment by jan-at-school** [comment]
> If I use Python 3:
> 
> ```
> Traceback (most recent call last):
>   File "gltf2usd.py", line 18, in <module>
>     from pxr import Usd, UsdGeom, Sdf, UsdShade, Gf, UsdSkel, Vt, Ar, UsdUtils
>   File "/Users/jimmygunawan/Projects/Pixar/BUILD/lib/python/pxr/Usd/__init__.py", line 24, in <module>
>     import _usd
> ModuleNotFoundError: No module named '_usd'
> ```

@enzyme69 

This error doesn't doesn't seem to be related with the your solution... 
How did you overcome this one? I am getting this error for python27 as well as python 3.
