### ISSUE TITLE
Black Shadow Visible When Viewed from Some Angle

### ISSUE THREAD

**Issue by ShantanuSriv** [kcoley/gltf2usd#107]
@kcoley When viewing the usdz model from some angles, it shows black shadow at the bottom but none of those are actually present in the glTF model.

Here is one example of it: 
glTF Model:

<img width="711" alt="screen shot 2018-11-19 at 3 18 27 pm" src="https://user-images.githubusercontent.com/29276040/48699419-68b29a00-ec0f-11e8-9247-d51e1c8d6495.png">

converted-usdz Model:

![image uploaded from ios](https://user-images.githubusercontent.com/29276040/48699477-8a138600-ec0f-11e8-8caf-213da9ac4a85.png)

Can you please look into the issue?

**Comment by ShantanuSriv** [comment]
@kcoley do you have any fix for this?

**Comment by kcoley** [comment]
Hi @ShantanuSriv. The shadow generation happens in AR Quicklook on Apple’s side.  It gets mentioned in this keynote video: 

https://developer.apple.com/videos/play/wwdc2018/603/

It looks to be incorrect based on your screenshot. Does it look bad when viewed in AR mode on a table or floor as well?

**Comment by ShantanuSriv** [comment]
@kcoley No, this is not a problem which I see in AR Quicklook only -- this is when I load the file in the normal viewer. Plus, this same issue is visible in AR Quicklook. So, it's not an issue which is specific to AR Quicklook. 

I remember that a similar issue was showing up earlier too - #95

**Comment by ShantanuSriv** [comment]
Mesh geometry
---------------

"meshes": [
    {
      "primitives": [
        {
          "attributes": {
            "POSITION": 1,
            "NORMAL": 2,
            "TEXCOORD_0": 3
          },
          "indices": 0,
          "mode": 4,
          "material": 0
        }
      ],
      "name": <some-name>
    }
  ],

Material
--------
"materials": [
    {
      "pbrMetallicRoughness": {
        "baseColorFactor": [
          1.0,
          1.0,
          1.0,
          1.0
        ],
        "baseColorTexture": {
          "index": 2,
          "texCoord": 0
        },
        "metallicFactor": 1.0,
        "roughnessFactor": 1.0,
        "metallicRoughnessTexture": {
          "index": 1,
          "texCoord": 0
        }
      },
      "normalTexture": {
        "index": 0,
        "texCoord": 0
      },
      "occlusionTexture": {
        "index": 1,
        "texCoord": 0
      },
      "emissiveFactor": [
        0.0,
        0.0,
        0.0
      ],
      "alphaMode": "BLEND",
      "name": "Material #25"
    }
  ]

Please tell me,if you need any more info on this.

**Comment by ShantanuSriv** [comment]
@kcoley do you have update on it?

**Comment by ShantanuSriv** [comment]
The issue is resolved. It was a device specific issue.

**Comment by kcoley** [comment]
Hi @ShantanuSriv just got back from vacation, but glad the issue is resolved
