### ISSUE TITLE
When node or object has stupid naming with bracket it failes to convert

### ISSUE THREAD

**Issue by enzyme69** [kcoley/gltf2usd#110]
I have this BLEND files in which the objects uses stupid naming like node[2], material[4] and it's giving error 🤯

**Comment by kcoley** [comment]
Hi @enzyme69 , can you provide a sample blender file?

**Comment by kcoley** [comment]
@enzyme69 a sample glTF file would be better.

**Comment by kcoley** [comment]
@enzyme69 closing for now.
