### ISSUE TITLE
Simple Transform Animation(s) Does Not Work (Again) and Stuttering

### ISSUE THREAD

**Issue by enzyme69** [kcoley/gltf2usd#111]
[anim_test_005.blend.zip](https://github.com/kcoley/gltf2usd/files/2627693/anim_test_005.blend.zip)
[USDZ_NoAnim.zip](https://github.com/kcoley/gltf2usd/files/2627694/USDZ_NoAnim.zip)

It's almost as if we are going back to zero, but maybe I did something wrong here.

So, in Blender I have 5 boxes, animated procedurally, just random wiggle translation XYZ, and all the animation is baked.

I exported using GLTF, with simple PBR material, and then I converted using USDZ like usual.

Suddenly there is no animation. 

Is animation now required to be Bones animation only?

**Comment by enzyme69** [comment]
The strange thing is GLTF 2.0 validation when I am using online GLTF Viewer:


Code | Message | Pointer
-- | -- | --
EMPTY_ENTITY | Entity cannot be empty. | /animations/0/channels
EMPTY_ENTITY | Entity cannot be empty. | /animations/0/samplers

**Comment by enzyme69** [comment]
Oookk... I figured it out. I really need to bake every single frames and there should not be gap? I use Blender "Bake Action" and it's all good now!

Thanks!!

**Comment by enzyme69** [comment]
However, now the animation is stuttering and only 1 out of 5 boxes working, I checked using online GLTF anim viewer, and it seems ok, although I need to turn on the action manually.

[USDZ_WeirdAnimStutter.zip](https://github.com/kcoley/gltf2usd/files/2627746/USDZ_WeirdAnimStutter.zip)

**Comment by kcoley** [comment]
Hi @enzyme69 .  I experimented with the fps by setting it to a smaller value like 10, to get a less stuttery result (--fps 10 ).  It might be related to sampling within the converter when converting to usdz and the animation interpolation on iOS/quicklook.

The converter currently only uses the first animation group in the glTF file.  If you were to load in this glTF viewer, you can pick which animation group you wish to use:

https://gltfviewer.babylonjs.com/
<img width="1231" alt="screen shot 2018-11-28 at 11 51 06 pm" src="https://user-images.githubusercontent.com/3946928/49206993-a1b5e180-f368-11e8-97e9-d6fb16902e33.png">


It is set up this way to avoid having two animation groups attempt to animate the same geometry.  I could add a flag to specify which animation group you want to export to the file.

**Comment by kcoley** [comment]
@enzyme69 closing for now, but feel free to reopen if need be
