### ISSUE TITLE
Blend Mode Not Getting Rendered Properly #95

### ISSUE THREAD

**Issue by ShantanuSriv** [kcoley/gltf2usd#112]
@kcoley Transparency issue is resolved to a great extent but there is one issue which I am not able to find a solution for -- I think the blend mode is not working properly.

Here is the glTF rendered file:
<img width="1072" alt="screen shot 2018-12-04 at 10 53 25 pm" src="https://user-images.githubusercontent.com/29276040/49460579-a6badb00-f817-11e8-8018-2e40e22366b4.png">

In the glTF rendered file, I see a thin pinkish-layer in the middle area where there is transparency.

In the usdz-converted file:

![image uploaded from ios 1](https://user-images.githubusercontent.com/29276040/49460917-82133300-f818-11e8-9155-ce02a1528ed1.png)

I see complete transparency. 

I think blend mode is not working fine with usdz. Do you have any proof of whether it's working fine?
I remember you saying that alphaMode: Mask is not yet supported for usdz. Can you provide the source for it? I was not able to find it.

If this is an altogether different issue, can you please look into it? It's a bit urgent. 

Thanks.

**Comment by kcoley** [comment]
Hi @ShantanuSriv.  The only thing I was able to confirm working with iOS was alpha blend, which I believe to be the only alpha mode currently supported in usdz specification.  I was not able to find anything about blend modes in the USD preview surface specification: https://graphics.pixar.com/usd/docs/UsdPreviewSurface-Proposal.html

I tested against these glTF models from the glTF-Asset-Generator project: https://github.com/KhronosGroup/glTF-Asset-Generator/tree/master/Output/Material_AlphaBlend

Is the bag supposed to be using alpha blend?

**Comment by kcoley** [comment]
@ShantanuSriv also is the alpha value set to a very low value, if using alpha blending?

**Comment by ShantanuSriv** [comment]
@kcoley 
> Is the bag supposed to be using alpha blend?

yes

**Comment by ShantanuSriv** [comment]
> @ShantanuSriv also is the alpha value set to a very low value, if using alpha blending?
@kcoley i have to base material and both of them use the same alpha value of 1 in baseColorFactor[3], having same baseColorTexture but one with alphaMode Blend and the other one with Opaque.

**Comment by kcoley** [comment]
@ShantanuSriv gotcha.  As a test, can you remove the "Blend" line from the glTF file and try converting to see if the result is the same when converting to usd?

**Comment by ShantanuSriv** [comment]
@kcoley sure, I will try that and see if it helps.

**Comment by kcoley** [comment]
@ShantanuSriv interesting, do you know what the alpha values are in the texture?

**Comment by kcoley** [comment]
@ShantanuSriv do you know if you can provide a simple mesh that can repro this issue?

**Comment by ShantanuSriv** [comment]
@kcoley gltf sample which for the above images. Can you please look into this? 
[53264118_mid.zip](https://github.com/kcoley/gltf2usd/files/2664058/53264118_mid.zip)

**Comment by kcoley** [comment]
@ShantanuSriv I'll take a look

**Comment by kcoley** [comment]
@ShantanuSriv this looks like a discrepancy between Mac OS and iOS.  

Viewing the usdz model on iOS does yield a result similar to your photo:
![img_2104](https://user-images.githubusercontent.com/3946928/49774710-7ad1a680-fcaa-11e8-8f21-8907564dcf1f.PNG)

However, rendering the model within XCode actually shows the pink hue on the texture:
<img width="918" alt="screen shot 2018-12-10 at 6 39 06 pm" src="https://user-images.githubusercontent.com/3946928/49774859-f6335800-fcaa-11e8-8499-7f57e02335b6.png">

I also get a similar result using Babylon.js's glTF viewer:
<img width="935" alt="screen shot 2018-12-10 at 6 33 01 pm" src="https://user-images.githubusercontent.com/3946928/49774752-a6549100-fcaa-11e8-81a2-983eb903977a.png">

So this seems like it may be a bug in iOS.  Maybe good to file an issue with Apple?

**Comment by ShantanuSriv** [comment]
@kcoley thanks for all the help. Closing the issue for now.
