### ISSUE TITLE
GLTF animation looks correct but USDZ is out of whack

### ISSUE THREAD

**Issue by enzyme69** [kcoley/gltf2usd#120]
Not sure what causing this issue of bone animation got separated.

I have a feeling the bone rig etc was not setup properly in the Spiderman Rig itself:

[Spiderman Amazing Rigged 2 2 CYCLE 009.blend 2.zip](https://github.com/kcoley/gltf2usd/files/2660581/Spiderman.Amazing.Rigged.2.2.CYCLE.009.blend.2.zip)

GLTF looks correct if I use the online GLTF viewer:

[exported_GLTF_issue_when_become_USDZ.zip](https://github.com/kcoley/gltf2usd/files/2660582/exported_GLTF_issue_when_become_USDZ.zip)

However as USDZ, it looks broken. Both weird on MacOS. But on iOS, the seems like the middle part of the body is separated.
[spiderB.usdz.zip](https://github.com/kcoley/gltf2usd/files/2660584/spiderB.usdz.zip)

This is an older version, IK anim is baked to FK. Bone is "not connected", typical Blender rig.
[Spiderman Amazing Rigged 2 2 CYCLE 007.blend.zip](https://github.com/kcoley/gltf2usd/files/2660585/Spiderman.Amazing.Rigged.2.2.CYCLE.007.blend.zip)

But anyhow, what I don't get is when seeing the animation looks correct as GLTF and it does not translate to USDZ.

**Comment by enzyme69** [comment]
I am using Kupoman GLTF export in Blender 2.79:
https://github.com/Kupoman/blendergltf

**Comment by kcoley** [comment]
@enzyme69 yeah looks like a skeleton export issue.  I plan on running this tool against these skin glTF unit test models: https://github.com/KhronosGroup/glTF-Asset-Generator/tree/master/Output/Animation_Skin

Hopefully this would help pin down where the issue is happening.

**Comment by ivan-ushakov** [comment]
@kcoley Maybe a separate issue, but what could be a reason when model stay in origin even if in animation we have it moving? It looks like when we disable root animation.

**Comment by enzyme69** [comment]
Hi Kacey, with iOS 13, usdzconvert and your tool, somewhat juggling both, I found this to be helpful:
- Clean bake FBX Export and Import
- Remove animation from Armature

And your tool seems to work where Apple one failed... oh well it's the hierarchy and armature thing!
