### ISSUE TITLE
Multiple Objects Rotating Animation Issue and PNG Transparency?

### ISSUE THREAD

**Issue by enzyme69** [kcoley/gltf2usd#121]
[santa_steve.zip](https://github.com/kcoley/gltf2usd/files/2669828/santa_steve.zip)

I have this 3 planes simply rotating in loop, I can see the GLTF animation looks correct, but when converted to USDZ, it's totally out of whack, wondering why...

And also is alpha transparency not yet supported with USDZ?

**Comment by enzyme69** [comment]
It should look like this:
![leanflippantcob-max-1mb](https://user-images.githubusercontent.com/3952687/49837112-59cb9b80-fdf9-11e8-9c7a-034aaca44d49.gif)

**Comment by enzyme69** [comment]
BLEND:
[AN_zoetrope_kaleidoscope_009_BAKED.blend.zip](https://github.com/kcoley/gltf2usd/files/2669852/AN_zoetrope_kaleidoscope_009_BAKED.blend.zip)

**Comment by kcoley** [comment]
@enzyme69 looks like the glTF is using cubic spline animations, which are not supported in usdz.  I haven't implemented a baking workaround for this yet in the tool.  Is it possible to author the model with linear animations or bake the animations from Blender?  That may work, though another issue you may hit is rendering planes in usdz, which might interfere with the shadow generation with ARQuicklook.  You might need to make the planes into 3D meshes.

**Comment by kcoley** [comment]
@enzyme69 I haven't yet found a way to support vertex color alpha in usdz, since the python API expects vertex color to not have an alpha component.

**Comment by enzyme69** [comment]
Thanks K, for explanation. I've been using multiple GLTF exporter, latest being the one from Blender 2.8 beta, but I think all of them are still WIP :D

**Comment by kcoley** [comment]
@enzyme69 closing for now
