### ISSUE TITLE
Error thrown when using GLTF Embedded file types 

### ISSUE THREAD

**Issue by wave-electron** [kcoley/gltf2usd#123]
@kcoley  I noticed today the tool seems to support GLTF "embedded" files as well? I had been using the separate type up until now. 

I did a few test files. Very simple just a cylinder geometry with a solid color, or png texture. I was getting errors thrown. see below

[test2.gltf.txt](https://github.com/kcoley/gltf2usd/files/2704689/test2.gltf.txt)

`python gltf2usd.py -g ./GLTF/test2.gltf -o test2.usdz -s 1
Traceback (most recent call last):
  File "gltf2usd.py", line 806, in <module>
    convert_to_usd(os.path.expanduser(args.gltf_file), os.path.abspath(os.path.expanduser(args.usd_file)), args.fps, args.scale, args.arkit, args.verbose, args.use_euler_rotation, args.optimize_textures)
  File "gltf2usd.py", line 754, in convert_to_usd
    usd = GLTF2USD(gltf_file=gltf_file, usd_file=usd_file, fps=fps, scale=scale, verbose=verbose, use_euler_rotation=use_euler_rotation, optimize_textures=optimize_textures)
  File "gltf2usd.py", line 55, in __init__
    self.gltf_loader = GLTF2Loader(gltf_file, optimize_textures)
  File "/Users/USDPython/USD/_gltf2usd/gltf2loader.py", line 118, in __init__
    self._initialize()
  File "/Users/USDPython/USD/_gltf2usd/gltf2loader.py", line 123, in _initialize
    self._initialize_images()
  File "/Users/USDPython/USD/_gltf2usd/gltf2loader.py", line 136, in _initialize_images
    self._images.append(GLTFImage.GLTFImage(image_entry, i, self, self._optimize_textures))
  File "/Users/USDPython/USD/_gltf2usd/gltf2/GLTFImage.py", line 21, in __init__
    if image_entry['uri'].startswith('data:image'):
KeyError: 'uri'

**Comment by wave-electron** [comment]
I just realised my version of gltf2usd was over a week old. I just updated to the latest release... and the error has gone. So closing this issue for now.

**Comment by wave-electron** [comment]
@kcoley BTW, doesn't have to be a character animation, just any geometry with image applied is crashing. I had a quick look in GLTFImage.py at the point the error occurs. It does not seem to handle the image_entry dict and falls over. I had a look at image_entry
{u' mimeType': u' image/png', u' bufferView': 0}

This line basically gives an error `if image_entry['uri'].startswith('data:image'):`

 which I'm guessing is not in the image_entry dict.

**Comment by wave-electron** [comment]
Test file I'm using 

[ImageTest.gltf.txt](https://github.com/kcoley/gltf2usd/files/2704906/ImageTest.gltf.txt)

**Comment by wave-electron** [comment]
@kcoley

https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/image.schema.json

It seems image can be referenced by either uri or bufferview. I’m guessing the gltf exporter I’m using is using the bufferview. If so, can the script easily incorporate this version of gltf?

**Comment by kcoley** [comment]
@wave-electron yeah I'll work on getting this in

**Comment by kcoley** [comment]
@wave-electron I just merged a fix for this: https://github.com/kcoley/gltf2usd/pull/124

[test.usdz.txt](https://github.com/kcoley/gltf2usd/files/2705863/test.usdz.txt)

**Comment by wave-electron** [comment]
Awesome work! I’m keen to start using the embedded gltf’s, so will let you know if I encounter any other issues.
