### ISSUE TITLE
Multiple Images assigned to mesh - not working on embedded GLTF variant

### ISSUE THREAD

**Issue by wave-electron** [kcoley/gltf2usd#125]
@kcoley If you have multiple images assigned to  the same mesh, the script seems to loop the correct amount of times, but copies the first image multiple times to the usdz archive. I've uploaded a gltf test file for you to use for testing if needed. 

[multipleImageTest.zip](https://github.com/kcoley/gltf2usd/files/2705985/multipleImageTest.zip)

**Comment by kcoley** [comment]
@wave-electron thanks for the model with multiple images.  I did not do the binary extraction properly in the last fix, but it seems to be working now after my last PR: https://github.com/kcoley/gltf2usd/pull/127

[test.usdz.txt](https://github.com/kcoley/gltf2usd/files/2706465/test.usdz.txt)
