### ISSUE TITLE
License file in usdz archive

### ISSUE THREAD

**Issue by wave-electron** [kcoley/gltf2usd#129]
This is a feature request.

What do others think about the need for a license/model credits txt file in the usdz archive? I personally think this is an issue with usdz at the moment. These 3D assets are shareable & currently when they get shared there is no way of knowing who is the license holder or should be getting credit.

**Comment by wave-electron** [comment]
Say for example I’m hosting usdz files on my website, that need to give model credits to third-parties. I can add license info or links on the weppage or usdz thumbnail. But once that usdz asset gets shared via iMessage or email. Potentially to millions. The license information or credits don’t deploy with the usdz archive. At least if it’s within the archive, I know if someone unzips the archive the license and model credits can be easily viewed.

**Comment by kcoley** [comment]
@wave-electron Unfortunately, the usdz api does not have an option for license files.  Though I think your idea may be a good request for the [usd interest group forum](https://groups.google.com/forum/#!forum/usd-interest).  This sounds similar to how glTF has copyright information in the `assets` section within the json.

**Comment by wave-electron** [comment]
@kcoley thanks for letting me know. When I get a chance will raise it in the usd interest group. I think it’s important because of the way usdz asset is built around being shareable via iMessage & email. The moment you share it, copyright is lost.
