### ISSUE TITLE
GLTF Material names not preserved

### ISSUE THREAD

**Issue by nikunjarora12345** [kcoley/gltf2usd#135]
After conversion to usdz, materials are renamed as "pbrmaterial_0" and similar instead of retaining the original names. Is retaining the original names possible?

**Comment by kcoley** [comment]
Hi @nikunjarora12345 .  I can make an update to make the names match the original if possible, as long as the name does not cause path conflicts in USD.

**Comment by nikunjarora12345** [comment]
@kcoley Thanks a lot. Hoping for a positive result.

**Comment by kcoley** [comment]
@nikunjarora12345 sorry for the delay.  Just merged a fix for this.
