### ISSUE TITLE
Wrong texture lookup - PbrMetallicRoughness class uses index of texture to lookup image

### ISSUE THREAD

**Issue by jclarkk** [kcoley/gltf2usd#142]
[wrong_lookup.zip](https://github.com/kcoley/gltf2usd/files/2817046/wrong_lookup.zip)
Hey,

In the attached example it seems like the code in Material.py is using the index here:
Material[6]['pbrMetallicRoughness']['baseColorTexture']['index'] 

To find the image which leads to an error since the index should be used to find the texture object in 'textures'.

**Comment by kcoley** [comment]
@jclarkk good catch, I'll work on a fix for this

**Comment by kcoley** [comment]
@jclarkk just merged a fix for this: https://github.com/kcoley/gltf2usd/pull/143

**Comment by jclarkk** [comment]
Great, thanks!
