### ISSUE TITLE
Valid glft file - results curious - would be grateful for any help

### ISSUE THREAD

**Issue by BinaryChunk** [kcoley/gltf2usd#146]
Having success moving my animation assets from FBX to USDZ for use in iOS apps. Thanks for all your bright posts on the subject. 

Pipeline: C4D > gltf2  > gltf2usd > Xcode > USDZ

This one little dino animation has me stumped. Seems to be a valid gltf2 asset. After conversion, it is not previewing correctly in finder OSX or iOS. 
Source Files are here  - https://bit.ly/2WTIC2y

Shown with 100, 10, and 1cm Cubes on 200cm surface

![screen shot 2019-02-13 at 1 32 25 pm](https://user-images.githubusercontent.com/11893048/52750307-1df3b480-2fa9-11e9-885e-0e2df246ced7.png)

Successful previews when viewed from SketchFab's AR Viewer:
![img_1112](https://user-images.githubusercontent.com/11893048/52750421-6c08b800-2fa9-11e9-9029-9de74ff0052a.png)
![img_1110](https://user-images.githubusercontent.com/11893048/52750422-6ca14e80-2fa9-11e9-9324-f721bd73f787.png)

**Comment by kcoley** [comment]
Hi @BinaryChunk.  glTF defaults to units of [meters](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#coordinate-system-and-units).  With initial testing, I found that usdz on iOS assumed centimeters.  By default, the a scale of 100 is applied to convert from meters to centimeters, but this can be overwritten by setting the `--scale` (or `-s`) command line flag.

Btw, previewing the glTF file in the Babylon.js sandbox (https://sandbox.babylonjs.com/) looks like this:
<img width="769" alt="screen shot 2019-02-13 at 5 43 48 pm" src="https://user-images.githubusercontent.com/3946928/52756658-f7d51100-2fb6-11e9-9243-ebb2355975fa.png">

Is this what you are expecting visually?

**Comment by kcoley** [comment]
Btw, you can also directly export to usdz from gltf2usd if that helps your workflow :)

**Comment by BinaryChunk** [comment]
Thanks Kacey

Yes gltf file is fine - it the conversion I am referring to - would be grateful if you would try and convert it using gltf2usd and see if you get similar results. - thanks 

Source Files are here - https://bit.ly/2WTIC2y

![img_1106](https://user-images.githubusercontent.com/11893048/52761580-1fd16e00-2fd1-11e9-84ed-a032de457305.png)

**Comment by kcoley** [comment]
@BinaryChunk I just tried this, and looks like it may be a bug in iOS.  It displays properly within XCode and Preview on Mac OS:
<img width="544" alt="screen shot 2019-02-14 at 10 41 40 pm" src="https://user-images.githubusercontent.com/3946928/52839123-d0ab3c00-30a9-11e9-8265-991ea7fd24d2.png">

<img width="918" alt="screen shot 2019-02-14 at 10 42 58 pm" src="https://user-images.githubusercontent.com/3946928/52839159-f0426480-30a9-11e9-913b-d16f6682114c.png">

I believe @wave-electron came up with a workaround for this scenario: https://github.com/kcoley/gltf2usd/issues/49#issuecomment-422679613

Does this help?

**Comment by BinaryChunk** [comment]
@kcoley Thanks! I will rework animation per @wave-electron comments - grateful for your help!

**Comment by kcoley** [comment]
@BinaryChunk no problem!
