### ISSUE TITLE
Material with the same name don't convert correctly.

### ISSUE THREAD

**Issue by sayduck-daniel** [kcoley/gltf2usd#147]
We got a gltf with 3 meshes, each uses a different material.

Those 3 materials have the same name in the glTF file. (As per the spec, the material name can be the same or even omitted)

The USDZ generated uses the same material for all 3 meshes.

**Comment by kcoley** [comment]
@sayduck-daniel I just merged a fix which appends the index to the material names: https://github.com/kcoley/gltf2usd/pull/148
