### ISSUE TITLE
Adding annotation 

### ISSUE THREAD

**Issue by lizylgit** [kcoley/gltf2usd#154]
I am using the library to convert my 3dobjects to usdz and am very pleased with the result. 
I have a requirement to  attach annotation to  3D objects, these annotations are not converted to  USDZ . The glTF 3DObject node contains the  the annotation information ex 'label text'  and the 'position' to place the annotation.  Are you able to help or direct me on how I can add these labels in USDZ for AR.  Thanks

**Comment by kcoley** [comment]
@lizylgit I made an update so data added to the extras on a node or the glTF asset data gets written out to customData
