### ISSUE TITLE
ModuleNotFoundError: No module named '_usd'

### ISSUE THREAD

**Issue by julien-c** [kcoley/gltf2usd#156]
Probably more of an issue with Apple's prebuilt usd library than with this module, but in case anyone has a fix or an idea how to solve:

```
Traceback (most recent call last):
  File "gltf2usd.py", line 18, in <module>
    from pxr import Usd, UsdGeom, Sdf, UsdShade, Gf, UsdSkel, Vt, Ar, UsdUtils
  File "/Users/gibbon/Desktop/USDPython/USD/pxr/Usd/__init__.py", line 24, in <module>
    import _usd
ModuleNotFoundError: No module named '_usd'
```

(I've added the `USD/` folder to both $PATH and $PYTHONPATH)

**Comment by julien-c** [comment]
(alternatively, if anyone could convert the .gltf below to .usdz I'd be super grateful – yes I'm lazy :)

[Arachnix-baked-subdiv.gltf.zip](https://github.com/kcoley/gltf2usd/files/3087492/Arachnix-baked-subdiv.gltf.zip)

**Comment by yspark90** [comment]
[arachnix.usdz.zip](https://github.com/kcoley/gltf2usd/files/3239762/arachnix.usdz.zip)

**Comment by julien-c** [comment]
Thanks so muck @yspark90

**Comment by jerinisready** [comment]
Traceback (most recent call last):
  File "gltf2usd.py", line 19, in <module>
    from pxr import Usd, UsdGeom, Sdf, UsdShade, Gf, UsdSkel, Vt, Ar, UsdUtils
  File "/home/jk/code/usdpython/USD/lib/python/pxr/Usd/__init__.py", line 24, in <module>
    import _usd
ImportError: /home/jk/code/usdpython/USD/lib/python/pxr/Usd/_usd.so: invalid ELF header
