### ISSUE TITLE
cannot import name _imaging

### ISSUE THREAD

**Issue by Betbe** [kcoley/gltf2usd#157]
I've been trying to run for two days this build but after looking for some info, asking to Jimmy and searching through the web I have not luck for a solution. I tried to do another user account in my Mac to restart all the process but neither I had any luck.

The same error is showing to me:
File "gltf2usd.py", line 16, in <module>
    from PIL import Image
  File "/Library/Python/2.7/site-packages/PIL/Image.py", line 93, in <module>
    from . import _imaging as core
ImportError: cannot import name _imaging

Any idea?
Thanks.

**Comment by kcoley** [comment]
@Betbe looks like you may have issues with your install of pillow (https://github.com/python-pillow/Pillow/issues/3088).
You can try installing with pip to see if that works better.
