### ISSUE TITLE
IK Bone animations won't work

### ISSUE THREAD

**Issue by dnxmvp24** [kcoley/gltf2usd#158]
Good day,

I tried out a simple Bone Animation using the pipeline. Apparently based on my self-study, only FK bone animations work as show below. I can't seem to find the right "solution" or way to make my human model walk using IK.

<img width="1437" alt="Screen Shot 2019-04-23 at 2 21 29 PM" src="https://user-images.githubusercontent.com/49896440/56559075-1b2dc500-65d3-11e9-934f-00f7bcb429cc.png">

<img width="1438" alt="Screen Shot 2019-04-23 at 2 19 46 PM" src="https://user-images.githubusercontent.com/49896440/56558968-e457af00-65d2-11e9-98c1-c45ae08a4084.png">

Thank you very much.

**Comment by yspark90** [comment]
It's not supported

**Comment by yspark90** [comment]
You can ask about getting support for IK's and USD here:

https://groups.google.com/forum/m/#!forum/usd-interest
