### ISSUE TITLE
Texture conversion ends up in white texture

### ISSUE THREAD

**Issue by sayduck-daniel** [kcoley/gltf2usd#159]
Somehow this glTF material gets its texture converted to a white map and the original textures get replace by white ones.

This was working before but somehow now it's not anymore. Any idea on your side why its broken?

[conver-me.zip](https://github.com/kcoley/gltf2usd/files/3206164/conver-me.zip)

**Comment by sayduck-daniel** [comment]
We find the problem.

When we create an USDZ in the same folder than our glTF with an ORM map (occlusion roughness metalness). The converter splits the O and somehow overrides the source file. After that, it uses the newly created file to create the R and M:

this files:
![68747470733a2f2f692e696d6775722e636f6d2f41424250774d462e706e67](https://user-images.githubusercontent.com/38907720/58160782-cb045a00-7c87-11e9-8f03-71c87bbef3c1.png)

become:
![68747470733a2f2f692e696d6775722e636f6d2f766671446364542e706e67](https://user-images.githubusercontent.com/38907720/58160802-d35c9500-7c87-11e9-8e52-9beae519ba37.png)

----

if you use a different folder:
![68747470733a2f2f692e696d6775722e636f6d2f7051637a4338572e706e67](https://user-images.githubusercontent.com/38907720/58160833-df485700-7c87-11e9-967b-af72ba93ab79.png)

**Comment by kcoley** [comment]
@sayduck-daniel just merged a fix so usd creation happens in a temp directory before being copied over to the specified directory
