### ISSUE TITLE
Animating on MacOS but not on iOS, maybe still "Armature/" related

### ISSUE THREAD

**Issue by enzyme69** [kcoley/gltf2usd#22]
I thought this one was already solved and I tried deleting all "Armature/" manually using USDA, but somewhat the USDZ is not working. Strange...

Example animation: (made using Blender Grease Pencil, exported as GLTF)
[greasepencil_quicky.zip](https://github.com/kcoley/gltf2usd/files/2342349/greasepencil_quicky.zip)

**Comment by enzyme69** [comment]
<img width="1456" alt="screen shot 2018-09-01 at 11 33 21 pm" src="https://user-images.githubusercontent.com/3952687/44946431-8d347c80-ae3f-11e8-9bd6-221761a89ad6.png">

Aha... I got it, I am an idiot! 👻

**Comment by enzyme69** [comment]
@wave-electron Yes it works! Ensure the "first name of the joint or bone" matches those for root. That's another gotcha, but @kcoley your Python GLTF 2 USDZ converter is so handy!

**Comment by wave-electron** [comment]
@enzyme69 Jimmy I'm not following what you mean by this. I've tried replacing  "Armature/" references to say "Armature_Bone/" in the same spots as your screenshot above... but the animation still does not run in IOS12 beta 12. It works however in xcode 10 beta 6.  Can you be more explicit with what you mean by....  ensure the first name of the joint or bone matches those for root?


> Yes it works! Ensure the "first name of the joint or bone" matches those for root. That's another gotcha, but @kcoley your Python GLTF 2 USD converter is so handy!

**Comment by wave-electron** [comment]
When I make those changes the animation will work in xcode beta6, but it previews in IOS12 Beta 12 but the animation does not run. I've uploaded the files for you to check if we're both on the same page. Note: the usdz may work on MAC, I'm still running on High Sierra OS, so cannot check that.
[quicky.zip](https://github.com/kcoley/gltf2usd/files/2350866/quicky.zip)

**Comment by wave-electron** [comment]
@enzyme69 Jimmy did you get a chance to look at this? I'd love some feedback.

**Comment by enzyme69** [comment]
@wave-electron You cannot have same name bone within the hierarchy. On MacOS Mojave, the USDZ animation works fine, but on iOS, it's more strict. 

Let me try to fix yours, I've been using Sublime to quickly replace same name bones ... one sec..

Believe it or not, I have been asked the same questions on this weird hierarchy name issue, no "Armature/" ... :D 

<img width="1680" alt="screen shot 2018-09-05 at 11 40 11 pm" src="https://user-images.githubusercontent.com/3952687/45097013-38f20b00-b165-11e8-8c72-036a3cd3c7c5.png">
<img width="1680" alt="screen shot 2018-09-05 at 11 39 47 pm" src="https://user-images.githubusercontent.com/3952687/45097014-38f20b00-b165-11e8-917e-1795ffe88358.png">
<img width="1680" alt="screen shot 2018-09-05 at 11 36 52 pm" src="https://user-images.githubusercontent.com/3952687/45097015-398aa180-b165-11e8-8026-fab280d6f5fa.png">
<img width="1089" alt="screen shot 2018-09-05 at 11 22 50 pm" src="https://user-images.githubusercontent.com/3952687/45097016-398aa180-b165-11e8-8dfd-dd5fab9384ff.png">

**Comment by wave-electron** [comment]
ok. Thats what I thought it was... but I've been finding it hard to fix that hierachy from within the usda file. Do you fix that inside Blender? If so could you screen shot how it looks. Thanks

**Comment by enzyme69** [comment]
I am fixing it using Sublime Text.

Basically "Find All" : "Armature/", whilst all highlighted, I deleted it.

<img width="1287" alt="screen shot 2018-09-05 at 11 47 40 pm" src="https://user-images.githubusercontent.com/3952687/45097453-42c83e00-b166-11e8-97ae-b21e82b68430.png">
[quicky_fixed.zip](https://github.com/kcoley/gltf2usd/files/2352995/quicky_fixed.zip)

**Comment by wave-electron** [comment]
Can you reload that zip again. I don't think you gave it enough time to upload

**Comment by wave-electron** [comment]
Jimmy got it. It works for me now on ios 12 as well. Appreciate that. I think that will help me fix many other bone animations I've been having problems with. :)

**Comment by wave-electron** [comment]
@enzyme69 @ox @kcoley Shouldn't this issue still be open?

Unfortunately, haven't had time myself to explore a coding solution, but it really requires one.

The only way I know to currently build a bone animation using gltf2usd tool required me to manually edit the usda file to make the animation run on IOS12 beta 12.  Whilst the animation does work in Xcode without the edit.... I would think most folks would ultimately require it just work on IOS as well. 

I've also found nearly every bone animation I've tried suffers from this joint name problem, except a couple of models I found in [KhronosGroup Samples glTF](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=2ahUKEwj9w7K34qndAhVHBIgKHSjGAS8QFjAAegQIBhAC&url=https%3A%2F%2Fgithub.com%2FKhronosGroup%2FglTF-Sample-Models&usg=AOvVaw0aL75CwkcKf6qaAeBABMKH)

**Comment by kcoley** [comment]
Yeah I am not sure how this was closed (might have been auto-closed by one of the other merged PRs).  I'll reopen this.

**Comment by ox** [comment]
@wave-electron yes this issue should still open. I'm digging through it right now. So far, the only real problem I see in @enzyme69's model is the lack of a root skeletal node (without '/' in it's path) in the "wrong" screenshot. Looking at the difference between the "quicky" models, I noticed that in `quickyX`,  the `"Armature_Bone"` skeleton has a root joint "Armature_Bone" (not to be confused with the skeleton name), whereas the broken one has an invalid root joint "Armature/Armature_Bone".

**Comment by ox** [comment]
@wave-electron BlendShape support was merged however I haven’t gotten animations to play. To be honest I haven’t seen any BlendShape USD models out on the Internet. I think that part of the schema is very new so we might be on the frontier on this one. I have successfully generated USD models from gltf models which has an animation channel with `“path”: “weights”`, but iOS refuses to render it. 

What exactly are you doing to get the skinning to work?

**Comment by wave-electron** [comment]
We might be able to request example from Pixar in the usd-interest group. Those guys seem fairly accommodating to requests. In respect to my animations with weights. I’m creating the animation in Cheetah 3D, exporting as a collada, importing into Blender to export as glTF 2. Then running the gltf2usd command line tool. Finally manually editing the file to fix the joint name. Then using usd_converter tool for final conversion. That’s it!

**Comment by wave-electron** [comment]
@ox  I tried out your patch above on the bananaMan.usdz above. I had to make the following edits manually to get it to work. If i didn't do this the animation was all distorted and broken!

Are you able to re-jig a patch to replace **Armature/Armature_Joint**  with **skel**?  

The edits in red marker 

<img width="886" alt="usdz_wrong" src="https://user-images.githubusercontent.com/16273780/45250486-6a422500-b377-11e8-86cd-8ae3321bbcfe.png">


Edited usda -   animates in IOS 12 correctly

<img width="937" alt="edited_usda" src="https://user-images.githubusercontent.com/16273780/45250429-3d414280-b376-11e8-8103-9b2fa155f656.png">

**Comment by enzyme69** [comment]
Exciting development in regards to blendshapes!! 

But you are right, it does not work as USDZ yet, maybe on Apple side. I don't know how Maya/Houdini/Katana handles this USD however, does it simply load and can render for Renderman or something?

Is there example by Apple, a USDZ with blendshapes that work, apart from Memoji?

[OUTPUT.zip](https://github.com/kcoley/gltf2usd/files/2363012/OUTPUT.zip)

![facecap_bs_failed](https://user-images.githubusercontent.com/3952687/45250501-9eb5e100-b377-11e8-81f7-45821d7e5862.gif)

**Comment by enzyme69** [comment]
Much simpler animation to test this "shapekeys" or "blendshapes".
[simplevirus.zip](https://github.com/kcoley/gltf2usd/files/2363029/simplevirus.zip)

The GLTF with blendshapes seems to work, I tested:
https://gltf-viewer.donmccurdy.com

**Comment by wave-electron** [comment]
@ox @enzyme69 @kcoley From Pixar  via usd-interest group 1st August 2018

>**On Blend Shapes**
 UsdSkel provides a fully featured encoding for Skeletons, geometry bindings, and Joint Animations for USD (with blend shape support anticipated in the coming year)

From Pixar via usd-interest group 8th Sept 2018

> I'm not sure what iOS 12 supports, but I can tell you we haven't implemented Maya blendshape import/export yet.  The schema has been written as part of UsdSkel, and we did some verification that the behavior matches Maya's conception of blendshapes, but it's still on our to-do list for get import/export working.  Also, UsdImaging doesn't visualize blenshapes yet, but that's true for UsdSkel as well at the moment.  We're hoping to work on that soon.

**Comment by ox** [comment]
@wave-electron I’m away from my computers this weekend but I’m glad that we are narrowing down the issue. I have so far avoided wading into the skinning and skeleton building code in gltf2usd, as it’s the most intricate, so my patches are still just exploratory. Would it be possible for you to share the bananaman gltf model so I can build a fix against it? 

It seems that first it’s important that the number of elements in all timesamples for each skeleton animation is the same as the number of tokens in that animstion’s `joints` array. Then that there is a root node and that it is the skeleton node? That last part doesn’t quite make sense since the [UskSkel] docs have skeleton animations where the joints array doesn’t make any mention of the skeleton as the root node. Maybe extra intermediate joints are being computed and added? I think @kcoley is way more familiar with the Skelton code at this point. 

[UsdSkel]: https://graphics.pixar.com/usd/docs/api/_usd_skel__schema_overview.html

**Comment by wave-electron** [comment]
When you do have chance later... take a look at this example by Apple on Skel animation with weights.

[soccerBall.usda.txt](https://github.com/kcoley/gltf2usd/files/2363057/soccerBall.usda.txt)

**Comment by ox** [comment]
@kcoley I interpreted the presence of the SkelRoot to just mean that there is a skeleton somewhere further down this stack. I’m still confused about why the skeleton name needs to be specified as the root joint even though the joints array is just to establish hierarchy using arbitrary but consistent naming. I really think it’s a mismatch of array lengths between the joints tokens and the timesample arrays. That _should_ fix bone animation, but now I’m not so sure.

**Comment by kcoley** [comment]
@ox ah, I learned at SIGGRAPH that this is a bug in the iOS implementation of USD.  I believe the convention is based on Maya's USD exporter, which names the skeleton root the same name as the root joint.  Renaming the joints is a workaround to get it to animate on iOS until the implementation is updated.

**Comment by kcoley** [comment]
@ox 
> I really think it’s a mismatch of array lengths between the joints tokens and the timesample arrays. That should fix bone animation, but now I’m not so sure

Yes, this is correct.  With the skeleton refactoring branch, the array lengths are now the same for all the joint tokens since the animation samples are now being interpolated based on sampling with the fps parameter.  This seems to be working with the models from Sketchfab, though I am chasing down an animation hierarchy issue, which causes some parts of an animated model to be detached and floating in the wrong location.  I plan to make a PR this weekend with the update so others can try it out,

**Comment by kcoley** [comment]
@ox no problem!  I spent a good chunk of time working on this over the weekend, though I will probably need one more day or two to finish integrating all my changes.  It's definitely a big refactor so it's probably safer to test out the PR once I create it to make sure everything is ironed out.

**Comment by kcoley** [comment]
I made a recent update on iOS to the next Beta (12.1) and it seems to resolve the root name issue.  Is anyone else able to confirm?

**Comment by wave-electron** [comment]
@kcoley Yes, that seems to be the case.

**Comment by kcoley** [comment]
Just merged a fix for this (https://github.com/kcoley/gltf2usd/pull/94)
