### ISSUE TITLE
Questions on embedded GLTF PBR Texture

### ISSUE THREAD

**Issue by enzyme69** [kcoley/gltf2usd#38]
Just now, I exported GLTF material from Blender, and during conversion, I am getting this error:

```
Traceback (most recent call last):
  File "gltf2usd.py", line 1126, in <module>
    convert_to_usd(args.gltf_file, args.usd_file, args.fps, args.scale, args.verbose)
  File "gltf2usd.py", line 1114, in convert_to_usd
    GLTF2USD(gltf_file=gltf_file, usd_file=usd_file, fps=fps, scale=scale, verbose=verbose)
  File "gltf2usd.py", line 70, in __init__
    self.convert()
  File "gltf2usd.py", line 1099, in convert
    self._convert_materials_to_preview_surface()
  File "gltf2usd.py", line 482, in _convert_materials_to_preview_surface
    primvar_st1_output=primvar_st1_output
  File "gltf2usd.py", line 1074, in _convert_texture_to_usd
    texture_name = self.unpack_textures_to_grayscale_images(image_name, color_components)
  File "gltf2usd.py", line 1035, in unpack_textures_to_grayscale_images
    raise Exception('Unsupported image type!: {}'.format(img.mode))
Exception: Unsupported image type!: RGBA
```

So far, I have tested 3D GLTF from Sketchfab only and never had issue. Only today I am setting up the shader based on GLTF Blend example. Then I exported the object and getting an error. It does not seem to like RGBA, maybe I should change it to JPG?

<img width="645" alt="screen shot 2018-09-05 at 1 01 18 pm" src="https://user-images.githubusercontent.com/3952687/45068646-cdc81a80-b10b-11e8-9f34-05383dd38358.png">

**Comment by enzyme69** [comment]
Works ok on Clay-Viewer:
<img width="553" alt="screen shot 2018-09-05 at 1 02 59 pm" src="https://user-images.githubusercontent.com/3952687/45068686-0831b780-b10c-11e8-80f6-5f90ed539651.png">

**Comment by enzyme69** [comment]
@kcoley This is the one:
[USDZ_donut_rgba_error.zip](https://github.com/kcoley/gltf2usd/files/2351105/USDZ_donut_rgba_error.zip)

Maybe the texture itself is problematic. Just now, I convert all the PNG into JPG and works!

**Comment by ox** [comment]
So the texture it's failing on is the Ambient Occlusion png, which has 4 channels. The `_convert_materials_to_preview_surface` function goes in expecting to use the `r` component of the `occulusionTexture` image as the occlusion map, sees a 4 channel image, which jumps to logic trying to unpack a glossiness map.

I think if you change your ao.png to only be 3 channels, it should work

**Comment by kcoley** [comment]
@enzyme69 yes what @ox says is correct since the logic initially assumes that you are using an ORM texture (occlusion: r, roughness: g, metallic: b).  The texture logic definitely needs refactoring.  I will look into that later today to make it more robust.  But in the meantime, @ox solution should work.

**Comment by enzyme69** [comment]
It makes me wonder if we actually have "Occlusion Transparency Shader" already ...
![weird_rgb](https://user-images.githubusercontent.com/3952687/45133428-75128380-b1d8-11e8-8145-c71c8fd9b792.gif)

**Comment by enzyme69** [comment]
@kcoley Do you mean in the Blender material node itself, I could have **Roughness - Metalness -Occlusion (**greyscale) plug into RGB node which will translate into GLTF and works with your conversion?

**Comment by enzyme69** [comment]
It's this Metalness and Roughness which unfortunate...
<img width="900" alt="screen shot 2018-09-07 at 7 03 32 am" src="https://user-images.githubusercontent.com/3952687/45185031-27475b00-b26c-11e8-962b-43130fd2ba7a.png">

**Comment by sulydeni** [comment]
> It makes me wonder if we actually have "Occlusion Transparency Shader" already ...
> ![weird_rgb](https://user-images.githubusercontent.com/3952687/45133428-75128380-b1d8-11e8-8145-c71c8fd9b792.gif)
I have a similar issue. My model does not reflect light the same way it does in gltf

**Comment by kcoley** [comment]
I recently merged a change to remove alpha channel based on alpha mode: https://github.com/kcoley/gltf2usd/pull/93
