### ISSUE TITLE
Issue converting GLFT and getting texture to properly render

### ISSUE THREAD

**Issue by scottstevens** [kcoley/gltf2usd#44]
I've been playing around with this and have been having an easy time converting GLFT's from around the web... but have been having a lot of problem getting ARKIT to properly render out the textures from assets of my own.  I was wondering if there was some insight that could be provided as to why my USDZ version is not working when the GLFT is fine.

I incidentally had to fix something locally to get this to convert (I havent sent a pull request for it yet)  The first line of _convert_texture_to_usd seems to have indexing problems when referencing the textures... ive fixed this by having it use the actual source:

`image_name = gltf_texture if (isinstance(gltf_texture, basestring)) else self.images[self.textures[gltf_texture['index']]['source']]`

(Source GLFT)
[DeclanChair_TobiasGravel.zip](https://github.com/kcoley/gltf2usd/files/2362700/DeclanChair_TobiasGravel.zip)

(USDZ)
[declan.zip](https://github.com/kcoley/gltf2usd/files/2362701/declan.zip)

**Comment by enzyme69** [comment]
@scottstevens I checked your USDZ with iOS 12 GM, seems to work!

**Comment by scottstevens** [comment]
I had gotten the model to show up but not with the proper textures.  It's
supposed to be tan (but ends up gray on the iPhone).  Did it show up tan
for you?

**Comment by kcoley** [comment]
Hi @scottstevens .  I have been doing some major refactoring in the code (almost done) on the refactor_skeleton branch.  In the process, I was able to get the texture to render correctly on iOS 12 GM.
[chair.usdz.zip](https://github.com/kcoley/gltf2usd/files/2389370/chair.usdz.zip)

I plan to have the PR ready pretty soon for others to test out.

**Comment by scottstevens** [comment]
@kcoley  Im a bit puzzled unless this is some issue with my install of USD.  Every time I run an asset I get this:

![sofa](https://user-images.githubusercontent.com/1002480/45637613-93963b80-ba70-11e8-8631-0328feea8f0d.jpg)

**Comment by scottstevens** [comment]
@kcoley I am seeing that the outputted PNG's from your version came out different than mine.  There must be some issue in the conversion of the PNG's.  I suspect it has something to do with me using a windows machine.

**Comment by kcoley** [comment]
Hi @scottstevens , yes sorry, I made the conversion on my `refactorSkeletons` branch: https://github.com/kcoley/gltf2usd/tree/refactorSkeletons

It's still work in progress, but you can give it a try with the models.  I am changing how I am loading textures using pillow, which fixes a bug with loading grayscale images.

**Comment by kcoley** [comment]
@scottstevens the update for this should now be in master
