### ISSUE TITLE
Material not rendering with some Animations models

### ISSUE THREAD

**Issue by wave-electron** [kcoley/gltf2usd#46]
Has anyone else successfully assigned materials or solid colors to multiple faces  incorporating animations?

So you might have a single mesh broken into mulitple faces, like animating a dinosaur, separate material assignment for say the eyes, body & claws. So 3 separate png files will be in the usdz archive each assigned to 3 different faces. 

I have successfully created several animations incorporating animations with only 1 material assignment for single mesh. All my posted bone animations on [fusionar gallery ](https://www.fusionar.app) were built with only one material assignment for a single mesh.

Note: For models that don't have any animations material assignment is working fine. It only seems to happen with models that incorporate animation. 

I had a look at the usda file.... it seems to have

**Comment by kcoley** [comment]
Hi @wave-electron.  Are you referring to multiple material assignments to a single mesh?  I think that is something that glTF 2.0 currently does not support.  Unless you are referring to something else?

**Comment by wave-electron** [comment]
Yes. Ok I didn’t know that about glTF 2.0. It’s probably better practice
just having the single material assignment anyway.
