### ISSUE TITLE
skeleton animations do not play on iOS

### ISSUE THREAD

**Issue by kcoley** [kcoley/gltf2usd#5]
- Make modifications to get skeleton animations to play on iOS

**Comment by kcoley** [comment]
Merged https://github.com/kcoley/gltf2usd/pull/4

**Comment by enzyme69** [comment]
Seems like this is the only line differences, but still investigating why so many different kind of GLTF, some works with animation and some does not.... 

<img width="1548" alt="screen shot 2018-08-23 at 5 15 16 pm" src="https://user-images.githubusercontent.com/3952687/44510519-3ec50680-a6f8-11e8-86e3-5786d23d605e.png">
