### ISSUE TITLE
Error when no BaseColorTexture and only BaseColorFactor

### ISSUE THREAD

**Issue by MrDChristop** [kcoley/gltf2usd#59]
Hi 
i have gltf models which have only a baseColorFactor and no baseColorTexture in the pbrMettalucRoughness material. When processing i get this error. I tested it and its because there is no texture. it gets the color somehow in the wrong format.

This fails
```
 "materials": [
        {
            "pbrMetallicRoughness": {
			   "baseColorFactor":[0,0,0,1.0],
               "metallicFactor": 0.0
            },
            "emissiveFactor": [
                0.0,
                0.0,
                0.0
            ],
            "name": "blinn3-fx"
        }
    ],
```

This succeeds using the same mode just changing the material definition
```
"materials": [
        {
            "pbrMetallicRoughness": {
			   "baseColorFactor":[0.9897612,0.964492261,0.9071641,1.0],
                "baseColorTexture": {
                    "index": 0
                },
                "metallicFactor": 0.0
            },
            "emissiveFactor": [
                0.0,
                0.0,
                0.0
            ],
            "name": "blinn3-fx"
        }
    ],
```

Here is the error i get. What would i need to do to fix that?
Thanks

_initialize_from_gltf_material
    self._set_khr_material_pbr_specular_glossiness(gltf_material)
  File "C:\Users\d_chr\Downloads\gltf2usd-master\Source\usd_material.py", line 166, in _set_khr_material_pbr_specular_glossiness
    self._set_pbr_metallic_roughness(gltf_material)
  File "C:\Users\d_chr\Downloads\gltf2usd-master\Source\usd_material.py", line 159, in _set_pbr_metallic_roughness
    self._set_pbr_base_color(pbr_metallic_roughness)
  File "C:\Users\d_chr\Downloads\gltf2usd-master\Source\usd_material.py", line 230, in _set_pbr_base_color
    self._diffuse_color.Set(tuple(base_color_scale))
pxr.Tf.ErrorException:
        Error in 'pxrInternal_v0_18__pxrReserved__::UsdStage::_SetValueImpl' at line 1522 in file c:\users\d_chr\downloads\usd-master\pxr\usd\lib\usd\stage.cpp : 'Type mismatch for </Materials/pbrmaterial_0/pbrMat.inputs:diffuseColor>: expected 'GfVec3f', got 'GfVec4d''

**Comment by kcoley** [comment]
Thanks for flagging this @MrDChristop !  It should be resolved now.
