### ISSUE TITLE
Multiple transform keyframe animations not working anymore

### ISSUE THREAD

**Issue by wave-electron** [kcoley/gltf2usd#69]
@kcoley I started using your new version since yesterday. It seems that multiple transform keyframe animations are not working in this new version. I have not looked into why just yet. But multiple keyframe transforms were definitely working in the previous version I have working examples which help me verified the issue. If you need a test file, let me know?

**Comment by kcoley** [comment]
@wave-electron thanks, a sample model would be great

**Comment by wave-electron** [comment]
@kcoley I created a quick example, 3 bouncing cubes on a surface. Both sets of files from different releases of gltf2usd.py.  
[cubeBounceFiles.zip](https://github.com/kcoley/gltf2usd/files/2454612/cubeBounceFiles.zip)

**Comment by wave-electron** [comment]
@kcoley I was just having a quick look at your gltf2usd.py master... in relation to this issue. I checked the usda file and it only seems to be building the first animation sequence for 1 cube out of 3 being animated.  

In your script gltf2usd.py at line 440. You've have the following in  
```
def _convert_animation_to_usd
animations = self.gltf_loader.get_animations()
 if len(animations) > 0:
            # only use first animation for now
            animation = animations[0]

```
From what I can determine from the comment and setting animation = animations[0] you're only looping over the first animation.... and you need a for loop to catch multiple keyframes.

Is that right?

**Comment by kcoley** [comment]
@wave-electron yeah that is right.  I'll push a fix for this
