### ISSUE TITLE
Failed at boost installation

### ISSUE THREAD

**Issue by sulydeni** [kcoley/gltf2usd#7]
I keep getting some compiling error when I first ran the USD installation script. I think it has something to do with python and boost. 
I have first got a boost installation error that say that there is an error running the below code

> ./b2 --prefix="/usr/local/USD" --build-dir="/usr/local/USD/build" -j2 address-model=64 link=shared runtime-link=shared threading=multi variant=release --with-atomic --with-date_time --with-filesystem --with-program_options --with-regex --with-system --with-thread --with-python install

then I ran it and I logged the results below, any ideas where this is coming from?

project-config.jam:24: syntax error at keyword =
project-config.jam:24: syntax error at keyword ;
warning: No toolsets are configured.
warning: Configuring default toolset "gcc".
warning: If the default is wrong, your build may not work correctly.
warning: Use the "toolset=xxxxx" option to override our guess.
warning: For more configuration options, please consult
warning: http://boost.org/boost-build2/doc/html/bbv2/advanced/configuration.html
Performing configuration checks

    - has_icu builds           : yes (cached)
    - lockfree boost::atomic_flag : yes (cached)

Component configuration:

    - atomic                   : building
    - chrono                   : not building
    - context                  : not building
    - coroutine                : not building
    - date_time                : building
    - exception                : not building
    - filesystem               : building
    - graph                    : not building
    - graph_parallel           : not building
    - iostreams                : not building
    - locale                   : not building
    - log                      : not building
    - math                     : not building
    - mpi                      : not building
    - program_options          : building
    - python                   : building
    - random                   : not building
    - regex                    : building
    - serialization            : not building
    - signals                  : not building
    - system                   : building
    - test                     : not building
    - thread                   : building
    - timer                    : not building
    - wave                     : not building

...patience...
...patience...
...found 24047 targets...
...updating 4 targets...
gcc.compile.c++ /usr/local/USD/build/boost/bin.v2/libs/thread/build/gcc-5.4.0/release/address-model-64/threading-multi/pthread/thread.o
In file included from ./boost/thread/detail/thread.hpp:21:0,
                 from ./boost/thread/thread_only.hpp:22,
                 from libs/thread/src/pthread/thread.cpp:11:
./boost/thread/detail/make_tuple_indices.hpp:35:26: warning: variadic templates only available with -std=c++11 or -std=gnu++11
     template <std::size_t...> struct tuple_indices
                          ^
./boost/thread/detail/make_tuple_indices.hpp:41:46: warning: variadic templates only available with -std=c++11 or -std=gnu++11
     template <std::size_t Sp, std::size_t ...Indices, std::size_t Ep>
                                              ^
./boost/thread/detail/make_tuple_indices.hpp:47:46: warning: variadic templates only available with -std=c++11 or -std=gnu++11
     template <std::size_t Ep, std::size_t ...Indices>
                                              ^
In file included from ./boost/thread/detail/thread.hpp:22:0,
                 from ./boost/thread/thread_only.hpp:22,
                 from libs/thread/src/pthread/thread.cpp:11:
./boost/thread/detail/invoke.hpp:242:51: warning: variadic templates only available with -std=c++11 or -std=gnu++11
     template <class Ret, class A, class A0, class ...Args>
                                                   ^
./boost/thread/detail/invoke.hpp:249:28: warning: variadic templates only available with -std=c++11 or -std=gnu++11
     invoke(Ret (A::*f)(Args...), BOOST_THREAD_RV_REF(A0) a0, BOOST_THREAD_RV_REF(Args) ...args)
                            ^
./boost/thread/detail/invoke.hpp:249:91: warning: variadic templates only available with -std=c++11 or -std=gnu++11
     invoke(Ret (A::*f)(Args...), BOOST_THREAD_RV_REF(A0) a0, BOOST_THREAD_RV_REF(Args) ...args)
                                                                                           ^
./boost/thread/detail/invoke.hpp:254:51: warning: variadic templates only available with -std=c++11 or -std=gnu++11
     template <class Ret, class A, class A0, class ...Args>
                                                   ^
./boost/thread/detail/invoke.hpp:261:28: warning: variadic templates only available with -std=c++11 or -std=gnu++11
     invoke(Ret (A::*f)(Args...) const, BOOST_THREAD_RV_REF(A0) a0, BOOST_THREAD_RV_REF(Args) ...args)
                            ^
./boost/thread/detail/invoke.hpp:261:97: warning: variadic templates only available with -std=c++11 or -std=gnu++11
     invoke(Ret (A::*f)(Args...) const, BOOST_THREAD_RV_REF(A0) a0, BOOST_THREAD_RV_REF(Args) ...args)
                                                                                                 ^
./boost/thread/detail/invoke.hpp:266:51: warning: variadic templates only available with -std=c++11 or -std=gnu++11
     template <class Ret, class A, class A0, class ...Args>
                                                   ^
./boost/thread/detail/invoke.hpp:273:28: warning: variadic templates only available with -std=c++11 or -std=gnu++11
     invoke(Ret (A::*f)(Args...) volatile, BOOST_THREAD_RV_REF(A0) a0, BOOST_THREAD_RV_REF(Args) ...args)
                            ^
./boost/thread/detail/invoke.hpp:273:100: warning: variadic templates only available with -std=c++11 or -std=gnu++11
     invoke(Ret (A::*f)(Args...) volatile, BOOST_THREAD_RV_REF(A0) a0, BOOST_THREAD_RV_REF(Args) ...args)
                                                                                                    ^
./boost/thread/detail/invoke.hpp:278:51: warning: variadic templates only available with -std=c++11 or -std=gnu++11
     template <class Ret, class A, class A0, class ...Args>
                                                   ^
./boost/thread/detail/invoke.hpp:285:28: warning: variadic templates only available with -std=c++11 or -std=gnu++11
     invoke(Ret (A::*f)(Args...) const volatile, BOOST_THREAD_RV_REF(A0) a0, BOOST_THREAD_RV_REF(Args) ...args)
                            ^
./boost/thread/detail/invoke.hpp:285:106: warning: variadic templates only available with -std=c++11 or -std=gnu++11
     invoke(Ret (A::*f)(Args...) const volatile, BOOST_THREAD_RV_REF(A0) a0, BOOST_THREAD_RV_REF(Args) ...args)
                                                                                                          ^
./boost/thread/detail/invoke.hpp:293:51: warning: variadic templates only available with -std=c++11 or -std=gnu++11
     template <class Ret, class A, class A0, class ...Args>
                                                   ^
./boost/thread/detail/invoke.hpp:300:28: warning: variadic templates only available with -std=c++11 or -std=gnu++11
     invoke(Ret (A::*f)(Args...), BOOST_THREAD_RV_REF(A0) a0, BOOST_THREAD_RV_REF(Args) ...args)
                            ^
./boost/thread/detail/invoke.hpp:300:91: warning: variadic templates only available with -std=c++11 or -std=gnu++11
     invoke(Ret (A::*f)(Args...), BOOST_THREAD_RV_REF(A0) a0, BOOST_THREAD_RV_REF(Args) ...args)
                                                                                           ^
./boost/thread/detail/invoke.hpp:305:51: warning: variadic templates only available with -std=c++11 or -std=gnu++11
     template <class Ret, class A, class A0, class ...Args>
                                                   ^
./boost/thread/detail/invoke.hpp:312:28: warning: variadic templates only available with -std=c++11 or -std=gnu++11
     invoke(Ret (A::*f)(Args...) const, BOOST_THREAD_RV_REF(A0) a0, BOOST_THREAD_RV_REF(Args) ...args)
                            ^
./boost/thread/detail/invoke.hpp:312:97: warning: variadic templates only available with -std=c++11 or -std=gnu++11
     invoke(Ret (A::*f)(Args...) const, BOOST_THREAD_RV_REF(A0) a0, BOOST_THREAD_RV_REF(Args) ...args)
                                                                                                 ^
./boost/thread/detail/invoke.hpp:317:51: warning: variadic templates only available with -std=c++11 or -std=gnu++11
     template <class Ret, class A, class A0, class ...Args>
                                                   ^
./boost/thread/detail/invoke.hpp:324:28: warning: variadic templates only available with -std=c++11 or -std=gnu++11
     invoke(Ret (A::*f)(Args...) volatile, BOOST_THREAD_RV_REF(A0) a0, BOOST_THREAD_RV_REF(Args) ...args)
                            ^
./boost/thread/detail/invoke.hpp:324:100: warning: variadic templates only available with -std=c++11 or -std=gnu++11
     invoke(Ret (A::*f)(Args...) volatile, BOOST_THREAD_RV_REF(A0) a0, BOOST_THREAD_RV_REF(Args) ...args)
                                                                                                    ^
./boost/thread/detail/invoke.hpp:329:51: warning: variadic templates only available with -std=c++11 or -std=gnu++11
     template <class Ret, class A, class A0, class ...Args>
                                                   ^
./boost/thread/detail/invoke.hpp:336:28: warning: variadic templates only available with -std=c++11 or -std=gnu++11
     invoke(Ret (A::*f)(Args...) const volatile, BOOST_THREAD_RV_REF(A0) a0, BOOST_THREAD_RV_REF(Args) ...args)
                            ^
./boost/thread/detail/invoke.hpp:336:106: warning: variadic templates only available with -std=c++11 or -std=gnu++11
     invoke(Ret (A::*f)(Args...) const volatile, BOOST_THREAD_RV_REF(A0) a0, BOOST_THREAD_RV_REF(Args) ...args)
                                                                                                          ^
./boost/thread/detail/invoke.hpp:398:42: warning: variadic templates only available with -std=c++11 or -std=gnu++11
     template <class Ret, class Fp, class ...Args>
                                          ^
./boost/thread/detail/invoke.hpp:405:68: warning: variadic templates only available with -std=c++11 or -std=gnu++11
     invoke(BOOST_THREAD_RV_REF(Fp) f, BOOST_THREAD_RV_REF(Args) ...args)
                                                                    ^
./boost/thread/detail/invoke.hpp:409:32: warning: variadic templates only available with -std=c++11 or -std=gnu++11
     template <class Ret, class ...Args>
                                ^
./boost/thread/detail/invoke.hpp:411:24: warning: variadic templates only available with -std=c++11 or -std=gnu++11
     invoke(Ret(*f)(Args... ), BOOST_THREAD_RV_REF(Args) ...args)
                        ^
./boost/thread/detail/invoke.hpp:411:60: warning: variadic templates only available with -std=c++11 or -std=gnu++11
     invoke(Ret(*f)(Args... ), BOOST_THREAD_RV_REF(Args) ...args)
                                                            ^
In file included from ./boost/bind/bind.hpp:29:0,
                 from ./boost/bind.hpp:22,
                 from ./boost/thread/detail/thread.hpp:29,
                 from ./boost/thread/thread_only.hpp:22,
                 from libs/thread/src/pthread/thread.cpp:11:
./boost/bind/arg.hpp: In constructor ‘boost::arg<I>::arg(const T&)’:
./boost/bind/arg.hpp:37:22: warning: typedef ‘T_must_be_placeholder’ locally defined but not used [-Wunused-local-typedefs]
         typedef char T_must_be_placeholder[ I == is_placeholder<T>::value? 1: -1 ];
                      ^
In file included from ./boost/thread/once.hpp:20:0,
                 from libs/thread/src/pthread/thread.cpp:17:
./boost/thread/pthread/once_atomic.hpp: At global scope:
./boost/thread/pthread/once_atomic.hpp:120:37: warning: variadic templates only available with -std=c++11 or -std=gnu++11
   template<typename Function, class ...ArgTypes>
                                     ^
./boost/thread/pthread/once_atomic.hpp:121:108: warning: variadic templates only available with -std=c++11 or -std=gnu++11
   inline void call_once(once_flag& flag, BOOST_THREAD_RV_REF(Function) f, BOOST_THREAD_RV_REF(ArgTypes)... args)
                                                                                                            ^
In file included from ./boost/tuple/tuple.hpp:33:0,
                 from ./boost/thread/detail/async_func.hpp:37,
                 from ./boost/thread/future.hpp:22,
                 from libs/thread/src/pthread/thread.cpp:19:
./boost/tuple/detail/tuple_basic.hpp: In function ‘typename boost::tuples::access_traits<typename boost::tuples::element<N, boost::tuples::cons<HT, TT> >::type>::const_type boost::tuples::get(const boost::tuples::cons<HT, TT>&)’:
./boost/tuple/detail/tuple_basic.hpp:228:45: warning: typedef ‘cons_element’ locally defined but not used [-Wunused-local-typedefs]
   typedef BOOST_DEDUCED_TYPENAME impl::type cons_element;
                                             ^
libs/thread/src/pthread/thread.cpp: In function ‘boost::detail::thread_data_base* boost::detail::get_current_thread_data()’:
libs/thread/src/pthread/thread.cpp:140:88: error: no matching function for call to ‘call_once(boost::once_flag&, void (&)())’
             boost::call_once(current_thread_tls_init_flag,create_current_thread_tls_key);
                                                                                        ^
In file included from ./boost/thread/once.hpp:20:0,
                 from libs/thread/src/pthread/thread.cpp:17:
./boost/thread/pthread/once_atomic.hpp:121:15: note: candidate: template<class Function, class ... ArgTypes> void boost::call_once(boost::once_flag&, boost::detail::thread_move_t<T>, boost::detail::thread_move_t<Args>...)
   inline void call_once(once_flag& flag, BOOST_THREAD_RV_REF(Function) f, BOOST_THREAD_RV_REF(ArgTypes)... args)
               ^
./boost/thread/pthread/once_atomic.hpp:121:15: note:   template argument deduction/substitution failed:
libs/thread/src/pthread/thread.cpp:140:88: note:   mismatched types ‘boost::detail::thread_move_t<T>’ and ‘void (*)()’
             boost::call_once(current_thread_tls_init_flag,create_current_thread_tls_key);
                                                                                        ^
In file included from libs/thread/src/pthread/thread.cpp:17:0:
./boost/thread/once.hpp:35:13: note: candidate: template<class Function> void boost::call_once(Function, boost::once_flag&)
 inline void call_once(Function func,once_flag& flag)
             ^
./boost/thread/once.hpp:35:13: note:   template argument deduction/substitution failed:
libs/thread/src/pthread/thread.cpp:140:88: note:   cannot convert ‘boost::detail::{anonymous}::create_current_thread_tls_key’ (type ‘void()’) to type ‘boost::once_flag&’
             boost::call_once(current_thread_tls_init_flag,create_current_thread_tls_key);
                                                                                        ^
libs/thread/src/pthread/thread.cpp: In function ‘void boost::detail::set_current_thread_data(boost::detail::thread_data_base*)’:
libs/thread/src/pthread/thread.cpp:146:88: error: no matching function for call to ‘call_once(boost::once_flag&, void (&)())’
             boost::call_once(current_thread_tls_init_flag,create_current_thread_tls_key);
                                                                                        ^
In file included from ./boost/thread/once.hpp:20:0,
                 from libs/thread/src/pthread/thread.cpp:17:
./boost/thread/pthread/once_atomic.hpp:121:15: note: candidate: template<class Function, class ... ArgTypes> void boost::call_once(boost::once_flag&, boost::detail::thread_move_t<T>, boost::detail::thread_move_t<Args>...)
   inline void call_once(once_flag& flag, BOOST_THREAD_RV_REF(Function) f, BOOST_THREAD_RV_REF(ArgTypes)... args)
               ^
./boost/thread/pthread/once_atomic.hpp:121:15: note:   template argument deduction/substitution failed:
libs/thread/src/pthread/thread.cpp:146:88: note:   mismatched types ‘boost::detail::thread_move_t<T>’ and ‘void (*)()’
             boost::call_once(current_thread_tls_init_flag,create_current_thread_tls_key);
                                                                                        ^
In file included from libs/thread/src/pthread/thread.cpp:17:0:
./boost/thread/once.hpp:35:13: note: candidate: template<class Function> void boost::call_once(Function, boost::once_flag&)
 inline void call_once(Function func,once_flag& flag)
             ^
./boost/thread/once.hpp:35:13: note:   template argument deduction/substitution failed:
libs/thread/src/pthread/thread.cpp:146:88: note:   cannot convert ‘boost::detail::{anonymous}::create_current_thread_tls_key’ (type ‘void()’) to type ‘boost::once_flag&’
             boost::call_once(current_thread_tls_init_flag,create_current_thread_tls_key);
                                                                                        ^
In file included from ./boost/system/system_error.hpp:14:0,
                 from ./boost/thread/exceptions.hpp:22,
                 from ./boost/thread/pthread/thread_data.hpp:10,
                 from ./boost/thread/thread_only.hpp:17,
                 from libs/thread/src/pthread/thread.cpp:11:
./boost/system/error_code.hpp: At global scope:
./boost/system/error_code.hpp:222:36: warning: ‘boost::system::posix_category’ defined but not used [-Wunused-variable]
     static const error_category &  posix_category = generic_category();
                                    ^
./boost/system/error_code.hpp:223:36: warning: ‘boost::system::errno_ecat’ defined but not used [-Wunused-variable]
     static const error_category &  errno_ecat     = generic_category();
                                    ^
./boost/system/error_code.hpp:224:36: warning: ‘boost::system::native_ecat’ defined but not used [-Wunused-variable]
     static const error_category &  native_ecat    = system_category();
                                    ^

    "g++"  -ftemplate-depth-128 -O3 -finline-functions -Wno-inline -Wall -pedantic -pthread -fPIC -m64 -Wextra -Wno-long-long -Wno-variadic-macros -Wunused-function -pedantic -DBOOST_ALL_NO_LIB=1 -DBOOST_SYSTEM_DYN_LINK=1 -DBOOST_THREAD_BUILD_DLL=1 -DBOOST_THREAD_DONT_USE_CHRONO -DBOOST_THREAD_POSIX -DNDEBUG  -I"." -c -o "/usr/local/USD/build/boost/bin.v2/libs/thread/build/gcc-5.4.0/release/address-model-64/threading-multi/pthread/thread.o" "libs/thread/src/pthread/thread.cpp"

**...failed gcc.compile.c++ /usr/local/USD/build/boost/bin.v2/libs/thread/build/gcc-5.4.0/release/address-model-64/threading-multi/pthread/thread.o...**
...skipped <p/usr/local/USD/build/boost/bin.v2/libs/thread/build/gcc-5.4.0/release/address-model-64/threading-multi>libboost_thread.so.1.55.0 for lack of <p/usr/local/USD/build/boost/bin.v2/libs/thread/build/gcc-5.4.0/release/address-model-64/threading-multi>pthread/thread.o...
...skipped <p/usr/local/USD/lib>libboost_thread.so.1.55.0 for lack of <p/usr/local/USD/build/boost/bin.v2/libs/thread/build/gcc-5.4.0/release/address-model-64/threading-multi>libboost_thread.so.1.55.0...
...skipped <p/usr/local/USD/lib>libboost_thread.so for lack of <p/usr/local/USD/lib>libboost_thread.so.1.55.0...
...failed updating 1 target...
...skipped 3 targets...

**Comment by kcoley** [comment]
hi @sulydeni .  From the errors, I'm not exactly sure the cause of your boost errors, though perhaps you can check your version of g++ to see if it supports c++11?  I have had luck building on Mac OS using clang.  If this helps, I initially used the GitHub project [usd-build-club](https://github.com/vfxpro99/usd-build-club), which offers a few ways to build the USD library.  If you are still hitting build issues, you may have some luck reaching out on the USD forums.

**Comment by kcoley** [comment]
Btw, which OS are you using to build USD?

**Comment by sulydeni** [comment]
running Ubuntu 16.04.4 LTS 
g++ 5.4.0 - will check if it supports and will get back

**Comment by sulydeni** [comment]
Issue resolved. I followed the same build procedures of https://github.com/PixarAnimationStudios/USD but this time ran @tlorach script from https://github.com/tlorach/USD_build/blob/master/scripts/boost.sh to build boost - it uses boost_1_62_0 instead of  boost_1_55_0.  I ran the script then I copied it over to USD libraries directory /usr/local/USD/src.

**Comment by kcoley** [comment]
Great!
