### ISSUE TITLE
mesh under the root mesh needs to be scaled to (1,1,1) for scaling to be correct

### ISSUE THREAD

**Issue by wave-electron** [kcoley/gltf2usd#76]
@kcoley I've also picked up that when you have a mesh under the root mesh hierarchy, if it doesn't have a 1,1,1 scale its won't correctly scale relative to the root mesh.  To fix this I scale the root to (1,1,1) and all my nested meshes to a (1,1,1) as a workaround. Usually a pain in the but if you forget to do it much pain later! 

BTW, the  GLTF input file is scaled correctly in the sandbox, so it seems like the usdz conversion is not handling the scaling correctly from GLTF.

**Comment by wave-electron** [comment]
Thankyou for those suggestion.

I’ll reproduce some test files, and post them for further analysis. :)

**Comment by wave-electron** [comment]
@MrDChristop @kcoley It took me sometime trying to reproduce these gltf/usd test files. It's also a tricky issue to fix, which is why I thought it was important to flag it in the first place.  

This is how the input GLTF file (previews in https://sandbox.babylonjs.com) which matches the original scene in Blender. 

<img width="400" alt="gltf" src="https://user-images.githubusercontent.com/16273780/46703084-5be67200-cc71-11e8-8402-6faae280af1d.png">

You get this usdz result when the mesh positions were not set to (0,0,0) & scale (1,1,1) under the root hierarchy. In this example the root hierarchy is also set to (0,0,0) & scale(1,1,1) for the root in the original before I convert to gltf2. I haven't had time to cross reference the usda and GLTF file for why the conversion doesn't match the original. I just know how to fix it at the moment so it doesn't occur. 

![usdz](https://user-images.githubusercontent.com/16273780/46703099-702a6f00-cc71-11e8-8b43-0a3f86c0f76c.png)

[test_files_scale_issue.zip](https://github.com/kcoley/gltf2usd/files/2462468/test_files_scale_issue.zip)

**Comment by kcoley** [comment]
@wave-electron thanks for flagging this. At first I thought it was related to a transform as well as animated transforms appending to each other, so I tried removing all transform operations which worked for the cubes. 

But that led to the plane being problematic. I’m not sure if it is an issue with the USD decompose transform code that I am using to decompose a transform matrix into individual translation, rotation and scale components, but the transform operation ends up being different than the original composed transform matrix (the plane end scene up vertical when decomposed but horizontal when using the original transform matrix). I didn’t have too much time to play with this last night, but I will try something out tonight to see if it will be more consistent.

**Comment by kcoley** [comment]
@wave-electron I think I understand what is happening here.  The transform node is getting applied to the keyframed positions, which is causing the cubes to get an additional transform operation.  Also, quaternion rotations are being ignored, so is causing some confusion in the final positions.

A potential solution I will test is to have all animation keyframes represented as transformation matrices instead of scale, rotate and translate attributes.

**Comment by kcoley** [comment]
@wave-electron I just merged a fix for this.  It had to do with applying both the animation positions and the node positions from glTF to the same xform, which causes transform issues in usd.
