### ISSUE TITLE
No animations

### ISSUE THREAD

**Issue by dbathily** [kcoley/gltf2usd#79]
Hi,

I don't know il it's a bug, but I don't have animations exported in the usd. I attached a gltf which you can try to convert.

[Archive.zip](https://github.com/kcoley/gltf2usd/files/2469005/Archive.zip)

**Comment by kcoley** [comment]
Hi @dbathily , I am able to repro this issue.  I'll look into a fix.

**Comment by kcoley** [comment]
@dbathily looks like this is related to the joint path name issue.  I was able to patch your file to get the animation to work:
[ArchivePatched.zip](https://github.com/kcoley/gltf2usd/files/2499547/ArchivePatched.zip)

Until I push a fix, a short term patch is to remove all paths before the joint name:

<img width="1058" alt="screen shot 2018-10-21 at 12 37 37 pm" src="https://user-images.githubusercontent.com/3946928/47271434-32113300-d52e-11e8-89be-5d7ee6945bb5.png">

to this:
<img width="1011" alt="screen shot 2018-10-21 at 12 37 49 pm" src="https://user-images.githubusercontent.com/3946928/47271435-363d5080-d52e-11e8-8eba-93618b4f43aa.png">

**Comment by dbathily** [comment]
Ok @kcoley We will do this.

Looking forward to your fix. Thank you

**Comment by kcoley** [comment]
@dbathily sorry for the delay on this, but just merged a fix (https://github.com/kcoley/gltf2usd/pull/94).  Feel free to reopen this if the issue comes up again.
