### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by MrDChristop** [kcoley/gltf2usd#81]
I think with all that changes its time to introduce versioning.
Put in somewhere a version number and please add a changelog text document.

Thanks

**Comment by kcoley** [comment]
@MrDChristop I agree, this is a good idea

**Comment by wave-electron** [comment]
@MrDChristop @kcoley I was thinking that myself. It’s a good idea.

**Comment by kcoley** [comment]
Just merged versioning support
