### ISSUE TITLE
Add direct usdz export support

### ISSUE THREAD

**Issue by kcoley** [kcoley/gltf2usd#9]
- Add an option for directly generating usdz files instead of generating USD/USDA/USDC first

**Comment by wave-electron** [comment]
This would be a good feature.

**Comment by ox** [comment]
I noticed that the `usdzip` tool just uses `Usd.ZipFileWriter.CreateNew(usdzFile)` and calls `addFile` to the zipfileWriter instance. Is this the way to go?

**Comment by kcoley** [comment]
@ox yep, that's one way to go. There is another call that specifically targets ARKit in the API:

`UsdUtils.CreateNewARKitUsdzPackage(usd_file, usdz_file)`
