### ISSUE TITLE
useSpecularWorkflow should be int, not bool

### ISSUE THREAD

**Issue by spiderworm** [kcoley/gltf2usd#91]
https://github.com/kcoley/gltf2usd/blob/a155617b86603df643f102ea510d2e3631c663d7/Source/_gltf2usd/usd_material.py#L290

https://graphics.pixar.com/usd/docs/UsdPreviewSurface-Proposal.html

Setting it incorrectly causes errors in usdview:

`Failed to compile shader (GL_FRAGMENT_SHADER): 0(790) : error C7011: implicit cast from "bool" to "int"`

**Comment by spiderworm** [comment]
#92

**Comment by kcoley** [comment]
Thanks for the PR @spiderworm!
